services:
  db:
    image: postgres:15
    container_name: db_image
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5430:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 app:app
    container_name: app_image
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - images_data:/app/images
      - logs_data:/app/logs
    ports:
      - "8000:8000"   # для прямого доступа
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_image
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - images_data:/images:ro
    ports:
      - "80:80"
    restart: unless-stopped

  backup:
    image: postgres:15-alpine
    container_name: backup_image
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - backup_data:/backups
      - ./backup.sh:/script/backup.sh:ro
    command: >
      sh -c "
        while true; do
          echo '=== Starting backup cycle ===' &&
          sh /script/backup.sh 2>&1 || echo 'Backup script exited with error' &&
          echo 'Sleeping for 24h...' &&
          sleep 86400
        done
      "
    restart: unless-stopped

volumes:
  db_data:
    name: db_data
  images_data:
    name: images_data
  logs_data:
    name: logs_data
  backup_data:
    name: backup_data